version: '3'

services:
  discord-bot:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - lavalink
      - mongodb
    volumes:
      - .:/usr/src/discord-bot
      - /usr/src/discord-bot/node_modules
    networks:
      - node-network
  mongodb:
    image: mongo:5.0.14
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

  lavalink:
    image: fredboat/lavalink:64632e6
    ports:
      - '2333:2333'
    volumes:
      - .:/opt/Lavalink
    networks:
      - node-network

volumes:
  dbdata:
  
networks:
  node-network:
    driver: bridge
