version: '3'

services:
  discord-bot:
    build: .
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - lavalink
      - mongodb
    volumes:
      - .:/usr/src/discord-bot
      - /usr/src/discord-bot/node_modules
    networks:
      - node-network
  mongodb:
    image: mongo
    command: mongod --port ${MONGODB_PORT}
    ports:
      - '${MONGODB_PORT}:${MONGODB_PORT}'
    volumes:
      - ./db:/data/db
    networks:
      - node-network

  lavalink:
    image: fredboat/lavalink:64632e6
    ports:
      - '${LAVALINK_PORT}:${LAVALINK_PORT}'
    volumes:
      - .:/opt/Lavalink
    networks:
      - node-network
  
networks:
  node-network:
    driver: bridge
